[project]
name = "expense-tracker-mcpserver"
version = "0.1.0"
description = "An MCP server for tracking expenses and credits"
readme = "README.md"
authors = [
    { name = "Akshat Bansal", email = "akshat13bansal@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastmcp>=4.0.5",
    "platformdirs",
]

[build-system]
requires = ["uv_build>=0.12.18,<0.13.0"]
build-backend = "uv_build"